name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SINGLE_FILE: "true"

jobs:
  build:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./cli

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
        cd EventGrid.Publisher.ConsoleApp
        dotnet publish -p:PublishSingleFile=$SINGLE_FILE --runtime win-x64 --configuration Release --no-self-contained --output ../../publish/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: cli
        path: ./publish/

  release-cli:
    name: Release the cli
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: cli
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.1
      with:
        filename: evgtpub-release.zip
    - uses: ncipollo/release-action@v1
      with:
        #artifacts: cli
        body: |
          # New release
        tag: release
        token: ${{ secrets.GITHUB_TOKEN }}        
