name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - uses: QwerMike/xpath-action@v1
      id: AssemblyVersion
      with:
        filename: 'cli/EventGrid.Publisher.ConsoleApp/EventGrid.Publisher.ConsoleApp.csproj'
        expression: '//Project/PropertyGroup/AssemblyVersion/text()'
    - uses: QwerMike/xpath-action@v1
      id: PackageVersion
      with:
        filename: 'cli/EventGrid.Publisher.ConsoleApp/EventGrid.Publisher.ConsoleApp.csproj'
        expression: '//Project/PropertyGroup/PackageVersion/text()'        
    - name: branch
      run: |
        echo "${{ steps.AssemblyVersion.outputs.result }}"
        echo "${{ steps.PackageVersion.outputs.result }}"
        echo "SHA 8 = ${GITHUB_SHA::8}" 
        echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
    - name: xml-replace-action
      uses: rvolo/xml-replace-action@v0.3
      with:
        filepath: 'cli/EventGrid.Publisher.ConsoleApp/EventGrid.Publisher.ConsoleApp.csproj'
        xpath: '//Project/PropertyGroup/FileVersion/text()'
        replace: '${{ steps.AssemblyVersion.outputs.result }}.${{ github.run_number }}'
    - uses: web3j/substr-action@v1.2
      id: hash
      with:
        value: ${{github.sha}}
        start: '0'
        length: '8'
    - name: xml-replace-action
      uses: rvolo/xml-replace-action@v0.3
      with:
        filepath: 'cli/EventGrid.Publisher.ConsoleApp/EventGrid.Publisher.ConsoleApp.csproj'
        xpath: '//Project/PropertyGroup/FileVersion/text()'
        replace: '${{ steps.PackageVersion.outputs.result }}+${{steps.hash.outputs.result}}'
