name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: xml-replace-action
      uses: rvolo/xml-replace-action@v0.3
      with:
        # path in filesystem to xml file
        filepath: "./cli/EventGrid.Publisher.ConsoleApp/EventGrid.Publisher.ConsoleApp.csproj"
        # Xpath to use when getting nodes
        xpath: "//Project/PropertyGroup/FileVersion/text()"
        # value to replace with
        replace: "2.0.0-beta"
